export type RecordOrder =
    | "NAME_ASCENDING"
    | "NAME_DESCENDING"
    | "DATE_ASCENDING"
    | "DATE_DESCENDING"
    | "PRICE_ASCENDING"
    | "PRICE_DESCENDING"
    | "CREATED_ASCENDING"
    | "CREATED_DESCENDING"
    | "UPDATED_ASCENDING"
    | "UPDATED_DESCENDING";
